// flow-typed signature: f569476691d2f29e46248fec50a88455
// flow-typed version: <<STUB>>/styled-components-breakpoint_v2.0.2/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components-breakpoint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components-breakpoint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-components-breakpoint/dist/cjs/core' {
  declare module.exports: any;
}

declare module 'styled-components-breakpoint/dist/cjs/index' {
  declare module.exports: any;
}

declare module 'styled-components-breakpoint/dist/esm/core' {
  declare module.exports: any;
}

declare module 'styled-components-breakpoint/dist/esm/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-components-breakpoint/dist/cjs/core.js' {
  declare module.exports: $Exports<'styled-components-breakpoint/dist/cjs/core'>;
}
declare module 'styled-components-breakpoint/dist/cjs/index.js' {
  declare module.exports: $Exports<'styled-components-breakpoint/dist/cjs/index'>;
}
declare module 'styled-components-breakpoint/dist/esm/core.js' {
  declare module.exports: $Exports<'styled-components-breakpoint/dist/esm/core'>;
}
declare module 'styled-components-breakpoint/dist/esm/index.js' {
  declare module.exports: $Exports<'styled-components-breakpoint/dist/esm/index'>;
}
