export const variables = {
  fontPrimary: '"OpenSans", sans-serif',
  fontPrimaryBold: '"OpenSansBold", sans-serif',
  fontPrimaryExtraBold: '"OpenSansExtraBold", sans-serif',
  fontSecondary: '"Favorit", sans-serif',
  fontOCR: '"OCR A Std", "Favorit", monospace',

  fontSizeTiny: '12px',
  fontSizeSmall: '14px',
  fontSizeNormal: '16px',
  fontSizeMedium: '18px',
  fontSizeLarge: '20px',
  fontSizeLarger: '24px',
  fontSizeLargest: '36px',
  fontSizeSuperLarge: '42px',
  fontSizeHuge: '48px',
  fontSizeMassive: '120px',
  fontWeightNormal: 'normal',
  fontWeightBold: 'bold',

  colorWhite: '#ffffff',
  colorNeutralLightest: '#f2f2f2',
  colorNeutralLighter: '#e4e4e4',
  colorNeutralLight: '#cccccc',
  colorNeutral: '#a1a1a1',
  colorNeutralDark: '#686868',
  colorNeutralDarkest: '#2a2a2a',
  colorNeutralExtraDark: '#060606',

  colorGreen: '#02bda5',
  colorGreenLight: '#89f1d4',
  colorGreenLightest: '#e5f9f3',
  colorGreenBright: '#07e9b2',
  colorGreenBrighter: '#56f4c8',
  colorGreenDark: '#3edbb5',

  colorBlue: '#1fc5ec',
  colorBlueLight: '#c6f3ff',
  colorBlueLightest: '#effcfd',
  colorBlueDark: '#00346b',

  boxShadowGreenSmall: '0 3px 9px rgba(2,189,165,0.40)',
  boxShadowNeutralSmall: '0 3px 9px rgba(0, 0, 0, 0.05)',
  boxShadowNeutralNormal: '0 6px 24px rgba(0, 0, 0, 0.1)',
  boxShadowNeutralLarge: '0 12px 48px rgba(0, 0, 0, 0.1)',

  zIndexArrow: 1000,
  zIndexHeader: 1000,
  zIndexHeroBackground: 10,
  zIndexHeroDevice: 20,
  zIndexHeroWords: 30,
  zIndexCardImage: 60,
  zIndexCardPlastic: 70,
  zIndexTimelineLine: 100,
  zIndexTimelineMilestone: 110,
  zIndexAboutFacts: 95,
  zIndexModal: 2010,
  zIndexModalOverlay: 2000,
  zIndexMarketplaceVisualContainer: 200,
  zIndexMarketplaceVisualCards: 210,
  zIndexMarketplaceVisualDeviceContainer: 240,
  zIndexMarketplaceVisualDeviceCards: 250,
  zIndexMarketplaceVisualDeviceCardContainer: 260,
  zIndexMarketplaceVisualDeviceCardContainerActive: 261,
  zIndexDisclaimer: 2000,
};

export default variables;
